services:
  - type: web
    runtime: node
    name: tasweq-growth-studio
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NITRO_PRESET
        value: render-com
      - key: HOST
        value: 0.0.0.0
